name: Build and test the Nix shell environment
on:
  workflow_dispatch:
  schedule:
    - cron: '40 3 * * *'

jobs:
  test:
    strategy:
      matrix:
        source:
          - { repo: "qmk/qmk_firmware", branch: "master" }
        nixPath:
          - nixpkgs=channel:nixos-21.05
          # nixpkgs=channel:nixos-unstable
        os:
          - ubuntu-latest
          - macos-latest
      fail-fast: false

    defaults:
      run:
        working-directory: qmk_firmware

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: "${{ matrix.nixPath }}"

      - name: Show nixpkgs version
        working-directory: .
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: ${{ fromJSON(secrets.CACHIX_SETTINGS_JSON).name }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Checkout the project source
        uses: actions/checkout@v2.4.0
        with:
          path: nix-devenv-qmk

      - name: Checkout the QMK firmware source
        uses: actions/checkout@v2.4.0
        with:
          path: qmk_firmware
          repository: ${{ matrix.source.repo }}
          ref: ${{ matrix.source.branch }}
          submodules: recursive

      - name: Update submodules
        run: make git-submodule

      - name: Build the Nix shell environment
        id: nix_shell
        run: nix-shell ../nix-devenv-qmk/shell.nix --run 'true'

      - name: Test AVR build using 'make'
        if: ${{ always() && (steps.nix_shell.outcome == 'success') }}
        run: nix-shell ../nix-devenv-qmk/shell.nix --run 'make planck/rev5:default'

      - name: Test Arm build using 'make'
        if: ${{ always() && (steps.nix_shell.outcome == 'success') }}
        run: nix-shell ../nix-devenv-qmk/shell.nix --run 'make planck/rev6:default'

      - name: Test 'make clean'
        if: ${{ always() && (steps.nix_shell.outcome == 'success') }}
        run: nix-shell ../nix-devenv-qmk/shell.nix --run 'make clean'

      - name: Force clean before testing 'qmk compile'
        if: ${{ always() && (steps.nix_shell.outcome == 'success') }}
        run: git clean -fdx

      - name: Test AVR build using 'qmk compile'
        if: ${{ always() && (steps.nix_shell.outcome == 'success') }}
        run: nix-shell ../nix-devenv-qmk/shell.nix --run 'qmk compile -kb planck/rev5 -km default'

      - name: Test Arm build using 'qmk compile'
        if: ${{ always() && (steps.nix_shell.outcome == 'success') }}
        run: nix-shell ../nix-devenv-qmk/shell.nix --run 'qmk compile -kb planck/rev6 -km default'

      - name: Test 'qmk clean'
        if: ${{ always() && (steps.nix_shell.outcome == 'success') }}
        run: nix-shell ../nix-devenv-qmk/shell.nix --run 'qmk clean'
